# Starter pipeline
trigger:
- main

pool: 
  vmImage: ubuntu-latest   # Use the Ubuntu image for the pool

steps:
- checkout: self
  
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


