trigger:
- main

pool: 'Default'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'  # Updated to match your installed Java version (17)
    mavenVersionOption: 'Path'  # Use a custom Maven installation
    mavenPath: 'C:\maven\apache-maven-3.9.1'  # Path to your Maven installation

