trigger:
- main  # Replace with your branch name if different

pool:
  name: Default  # Use the Default agent pool

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your pom.xml file
    goals: 'clean install'     # Maven goals to execute
    publishJUnitResults: true   # Publish JUnit test results
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Path to test results
    javaHomeOption: 'JDKVersion' # Specify the JDK version
    jdkVersionOption: '17'       # Change to the desired JDK version (e.g., 17)
    jdkArchitectureOption: 'x64'  # Architecture of JDK
    mavenOptions: '-Xmx3072m'    # Optional Maven options
                           # Maven goal to package the project (creates a JAR or WAR)
