# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: 
  vmImage: windows-latest  # Use a Windows agent with pre-installed Maven

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'                      # Path to the pom.xml file
    mavenOptions: '-Xmx3072m'                    # Set the maximum memory allocation for Maven
    javaHomeOption: 'JDKVersion'                 # Specify to use a particular JDK version
    jdkVersionOption: '1.11'                     # JDK version 11
    jdkArchitectureOption: 'x64'                 # 64-bit architecture
    publishJUnitResults: true                    # Publish JUnit test results
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Test result files pattern
    goals: 'package'                             # Maven goal to package the project (creates a JAR or WAR)
