# Maven
# Build your Java project and run tests with Apache Maven.

trigger:
- main

pool:
  name: testpool  # Use your custom agent pool

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your pom.xml file
    mavenOptions: '-Xmx3072m'  # Maven options (optional)
    javaHomeOption: 'JDKVersion'  # JDK version to use
    jdkVersionOption: '17'  # Change to 17 if that's your installed version
    jdkArchitectureOption: 'x64'  # Architecture of JDK
    publishJUnitResults: true  # Publish JUnit test results
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Path to test results
    goals: 'package'  # Goals to run (e.g., clean, install, package)
  
- script: |
    echo "Build succeeded!"
  displayName: 'Success Message'

- script: |
    echo "Build failed. Please check the logs."
  condition: failed()
  displayName: 'Failure Message'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target'  # Path to the directory where artifacts are stored
    ArtifactName: 'JavaBuildArtifacts'  # Name of the published artifact
    publishLocation: 'Container'  # Publish location


