trigger:
- main

# Use Microsoft-hosted agent (after parallelism is granted)
pool:
  vmImage: 'ubuntu-latest'  # Or 'windows-latest' for Windows

steps:
- checkout: self
  
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
  displayName: 'Run a multi-line script'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'



