# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: testpool  # Using your custom agent pool

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your pom.xml file
    mavenOptions: '-Xmx3072m'  # Maven options (optional)
    javaHomeOption: 'JDKVersion'  # JDK version to use
    jdkVersionOption: '11'  # Adjust to your Java version
    jdkArchitectureOption: 'x64'  # Architecture of JDK
    publishJUnitResults: true  # Publish JUnit test results
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Path to test results
    goals: 'package'  # Goals to run (e.g., clean, install, package)
